export const imagePath:any = {
    user: require('./icons/user.png'),
    email: require('./icons/mail.png'),
    lock: require('./icons/lock.png'),
    eye_open: require('./icons/eye.png'),
    eye_close: require('./icons/hidden.png'),
    search_icon: require('./icons/search_icon.png'),
    login_watermark: require('./images/login_watermark.jpg'),
    breakfast: require('./icons/breakfast.png'),
    lunch: require('./icons/meal.png'),
    dinner: require('./icons/dinner.png'),
    dessert: require('./icons/dessert.png'),
    snack: require('./icons/snaks.png'),
    drinks: require('./icons/drink.png'),
    dietary: require('./icons/dietary.png'),
}